Docker
RayzOnePy/Backend pull request #1
Opened 2023-10-13 05:04 UTC by RayzOnePy

2023-10-13 05:40 UTC, RetmixX requested changes
По заданию должны использоваться образы на alpine
Убирай этот бабач и лучше посмотри в сторону php-fpm
Пример настройки nginx + php-fpm: https://miac.volmed.org.ru/wiki/index.php/Docker-compose_%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0_%D0%B4%D0%BB%D1%8F_%D1%81%D0%B0%D0%B9%D1%82%D0%B0_NGINX_%2B_MYSQL_%2B_PHP-FPM

2023-10-13 05:40 UTC, RetmixX commented on .env
Когда проект заливают в публичный репозиторий, создают .env.example, в котором прописывают, какие переменные окружения необходимы. Когда человек загружает к себе этот репозиторий, он создает клон .env.example с названием .env и прописывает свои значения для переменных окружения

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
>      image: postgres:alpine
Здесь лучше указать конкретную версию image, чтобы в будущем внезапно что-то не отвалилось из-за новой версии image

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
> +      - 5432:5432
Порт вынести в .env

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
> +      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
Лучше заранее подумать о дефолтном значении данных переменных. Что-то типо такого ${POSTGRES_USER:-user}

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.development.yml
> +  # db:
Убрать

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.development.yml
> +  nginx:
Без указания iamge или dockerfile, сервис не будет собираться

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.development.yml
> +  api:
Тоже самое

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
>        - 80:80
Порт так же вынести в .env

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
>      build: /Tasks/hello_world
Такая запись не подойдет. Контейнер не собирается

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
> +      - backend-network
Молодец, что используешь  отдельные сети

2023-10-13 05:40 UTC, RetmixX commented on docker-compose.yml
>        - "8080:80"
Порты так же вынести в .env

2023-10-13 06:50 UTC, jurapro requested changes
- не увидел в чем собственно у тебя разница прода и дева;
- куча мелких замечаний, нужно почистить
- окружение нужно проверять, чтобы оно поднималось))

2023-10-13 06:50 UTC, jurapro commented on docker-compose.yml
>        - 80:80
там что-то вроде такого должно быть ${WEB_PORT:-80}

2023-10-13 15:26 UTC, RayzOnePy reviewed
я кину новый merge-request с исправленными ошибками

2023-10-13 15:26 UTC, RayzOnePy commented on docker-compose.yml
>      image: postgres:alpine
пробовал поставить конкретную версию, почему-то крашится. 3 версии пробовал, последняя [13.10-alpine]

2023-10-13 15:26 UTC, RayzOnePy commented on docker-compose.yml
>      build: /Tasks/hello_world
мне нужно создать свой собственный образ и запушить на докер хаб? просто у меня контейнер собирается

2023-10-13 16:12 UTC, RayzOnePy commented on docker-compose.yml
>      build: /Tasks/hello_world
разобрался

2023-10-14 02:16 UTC, RetmixX requested changes
Молодец, что поправил замечания. По поводу разделения дев на прод. Хорошей практикой будет, если ты создашь отдельную папку для запуска приложения и внутри этой папки создашь подпапки для дева и прода, и там уже свои образы и docker compose файлы. + будет удобно запускать разные версии без дополнительного прописывания флагов для команды docker compose(типо docker compose -f ....)
У конфига прод версии nginx желательно так же внедрить переменные окружения для server_name и портов.

2023-10-14 02:16 UTC, RetmixX commented on images/php/Dockerfile
> +FROM php:8.1-fpm
Для php-fpm есть образ на основе alpine: php:8.1-fpm-alpine

2023-10-14 02:16 UTC, RetmixX commented on .env
Этот файл с заполненными переменными должен находится только у пользователя, который ведет работу. Его надо выносить в .gitignore, чтобы гит не отслеживал этот файл.

2023-10-14 02:16 UTC, RetmixX commented on .env.example
Тут просто название переменных должны быть без заполнения, это просто отображение того, какие переменные окружения требуются приложению.

2023-10-14 04:53 UTC, RayzOnePy commented
хорошо, спасибо. я завтра скину исправления

2023-10-15 16:34 UTC, jurapro requested changes
А ты свою сборку проверял на php файлах? Я не разворачивал ее, но есть подозрение что у тебя настройка коннекта с php-fpm нету в nginx. Примеров в интернете куча, вот первый попавшийся https://blog.devsense.com/2019/php-nginx-docker
Как проверишь работоспособность, заново на пулреквест, будем дальше смотреть)

2023-10-16 02:42 UTC, RetmixX requested changes
поправить замечания

2023-10-16 02:42 UTC, RetmixX commented on dockers/dev/data/asd.php
Можешь убрать этот файл

2023-10-16 02:42 UTC, RetmixX commented on dockers/dev/docker-compose.yml
> +    image: adminer
Версию у alpine укажи

2023-10-16 02:42 UTC, RetmixX commented on dockers/dev/nginx/conf.d/nginx.conf
> +    location /qwerty {
Это убрать

2023-10-16 02:42 UTC, RetmixX commented on dockers/dev/nginx/conf.d/nginx.conf
> +    location / {
Это тоже убрать

2023-10-16 02:42 UTC, RetmixX commented on dockers/prod/public/index.html
убрать

2023-10-16 02:42 UTC, RetmixX commented on dockers/prod/nginx/conf.d/nginx.conf
> +    location / {
убрать

2023-10-16 02:42 UTC, RetmixX commented on dockers/prod/images/php/Dockerfile
> +ADD php.ini /usr/local/etc/php/conf.d/40-custom.ini
добавь этот файл себе в проект

2023-10-16 12:38 UTC, RetmixX approved these changes
Все работает, молодец. Доступ к админеру лучше вынеси в конфиг девовского нджинкса и тогда вообще будет имба

2023-10-16 13:06 UTC, jurapro requested changes
Исправляй замечания и на повтор

2023-10-16 13:07 UTC, jurapro approved these changes

2023-10-16 13:52 UTC, merged