Oop(2)
RayzOnePy/Backend pull request #4
Opened 2023-10-23 15:03 UTC by RayzOnePy

Вторая часть курса ооп

2023-10-24 02:08 UTC, RetmixX requested changes
"SLQ Injection? Не, не слышал"
![image](https://github.com/RayzOnePy/Backend/assets/98283896/ccb95cb8-d85d-402a-b93f-771046ca72f2)

Погугли про prepare statement в PDO

2023-10-24 02:09 UTC, RetmixX commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +        $entities = $db->query(
injection

2023-10-24 02:09 UTC, RetmixX commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +        return $db->query('select * from ' . static::getTableName() . ';', [], static::class);
injection

2023-10-24 02:09 UTC, RetmixX commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +        $sql = 'UPDATE ' . static::getTableName() . ' SET ' . implode(', ', $columns2params) . ' WHERE id = ' . $this->id;
injection

2023-10-24 02:09 UTC, RetmixX commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +        $sql = 'INSERT INTO ' . static::getTableName() . '(' . implode(', ', $columns) . ')' . ' VALUES (' . implode(', ', $params) . ' )';
injection

2023-10-24 02:10 UTC, RetmixX commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +            'DELETE FROM ' . static::getTableName() . ' WHERE id = :id',
injection

2023-10-24 08:07 UTC, jurapro requested changes
- [ ] взаимодействие с БД организовать через PDO

2023-10-24 08:07 UTC, jurapro commented on project/week1/oop/part2/Models/ActiveRecordEntity.php
> +        $entities = $db->query(
Глянь в сторону PDO

2023-10-24 09:37 UTC, RayzOnePy commented
я же и так все делаю через pdo. 
![image](https://github.com/RayzOnePy/Backend/assets/99681039/81b196cd-3b39-4266-b255-34b4426dad5e)
вот код базы данных, там подготавливаю prepare и потом выполняю execute с параметрами. все взаимодействие с бд проходит через эту функцию

2023-10-25 01:35 UTC, jurapro approved these changes
Вопрос про PDO снят. Не внимательно посмотрел

2023-10-25 06:44 UTC, merged